package bootstrap

import "strings"

// Layout describes how a dotfiles repository stores package contents.
type Layout string

const (
	// LayoutPrefixed is the historical layout, where dotfiles are stored
	// with a dot- prefix, such as dot-vim/dot-vimrc. Package name mapping
	// translates those names on install.
	LayoutPrefixed Layout = "prefixed"

	// LayoutFullTree stores package contents as real dotfile paths, such as
	// nvim/.config/nvim/init.lua. Nothing needs translating, so package name
	// mapping must be turned off for the repository.
	LayoutFullTree Layout = "full-tree"
)

// dotPrefix is the package name prefix used by the prefixed layout.
const dotPrefix = "dot-"

// DetectLayout classifies a repository from its packages.
//
// The argument maps each package name to the names of its top-level entries.
// Detection is deliberately shallow, one directory level per package, and
// applies these rules in order:
//
//  1. Any package name or top-level entry carrying the dot- prefix means the
//     prefixed layout, even if other packages look like full trees.
//  2. Otherwise, any top-level entry that is itself a dotfile, such as
//     .config or .zshrc, means the full-tree layout.
//  3. Anything else is reported as prefixed, the historical default.
func DetectLayout(packages map[string][]string) Layout {
	fullTree := false

	for name, entries := range packages {
		if strings.HasPrefix(name, dotPrefix) {
			return LayoutPrefixed
		}

		for _, entry := range entries {
			if strings.HasPrefix(entry, dotPrefix) {
				return LayoutPrefixed
			}
			if strings.HasPrefix(entry, ".") {
				fullTree = true
			}
		}
	}

	if fullTree {
		return LayoutFullTree
	}

	return LayoutPrefixed
}

// RepoConfigYAML returns the repository configuration for a full-tree layout.
//
// It is written to .config/dot/config.yaml in the repository so that every
// later dot command in that repository leaves package names alone.
func RepoConfigYAML() []byte {
	return []byte(`# Repository configuration for dot.
# Generated by dot clone bootstrap.
#
# This repository stores package contents as real dotfile paths, so package
# names must not be translated on install.
dotfile:
  package_name_mapping: false
`)
}
